---
# tasks file for ansible-role-template
- name: create callback_plugins directory in playbook
  shell: "mkdir {{ PLAYBOOKS_PATH }}/{{ PLAYBOOK_TO_PROFILE }}"
  PLUGIN_DIR: "{{ PLAYBOOKS_PATH }}/{{ PLAYBOOK_TO_PROFILE }}/callback_plugins"

- name: clone plugin to subspace
  git:
    repo: "{{ PLUGIN_URI }}"
    dest: "{{ SUBSPACE_DIR }}"
    clone: yes

- name: clone plugin git repo
  git:
    repo: "{{ PLUGIN_URI }}"
    dest: "{{ PLUGIN_DIR }}"
    clone: yes

- name: compile plugin
  shell: |
    "python -m py_compile {{ PLUGIN_DIR }}/profile_tasks.py"
    "python -m py_compile {{ PLUGIN_DIR }}/config.py"
    "python -m py_compile {{ SUBSPACE_DIR }}/profile_tasks.py"  
    "python -m py_compile {{ SUBSPACE_DIR }}/config.py"

- name: create metrics database
  postgresql_db:
    name: metrics
    state: restore
    target: ./metrics_db.pgsql
